"""Dynamic scraper — executes a saved ScrapeStrategy generated by the discovery agent.

Two strategy types:
- api_intercept: Use httpx to make the exact request specified in the strategy.
  Traverse response via result_path and mapping to extract jobs.
- dom_selector: Boot Playwright, extract elements via result_path CSS selector,
  map attributes using mapping config.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from urllib.parse import urljoin

import httpx

from roleminer.scrapers.base import Job

logger = logging.getLogger(__name__)

_TIMEOUT_MS = 25_000
_IDLE_WAIT_MS = 6_000
_MAX_PAGES = 40
_PAGE_SIZE = 50


async def scrape_dynamic(
    company_url: str,
    strategy: dict,
    session: httpx.AsyncClient,
    company_name: str = "",
) -> tuple[list[dict], bool]:
    """Execute a saved ScrapeStrategy and return normalised job snapshots.

    Args:
        company_url: Fallback URL (the company's careers page).
        strategy: Validated strategy dict with strategy_type and config.
        session: httpx async client for API calls.
        company_name: Company name for Job objects.

    Returns:
        (jobs_as_dicts, http_was_ok) — list of job snapshot dicts and
        whether the HTTP response was 200 (used for self-healing: if
        http_was_ok but 0 jobs, the strategy is stale).
    """
    strategy_type = strategy.get("strategy_type", "")
    config = strategy.get("config", {})

    if strategy_type == "api_intercept":
        jobs, ok = await _scrape_api(config, session, company_name, company_url)
    elif strategy_type == "dom_selector":
        jobs, ok = await _scrape_dom(config, company_name, company_url)
    else:
        logger.warning(
            "[dynamic] unknown strategy_type=%s for company=%r",
            strategy_type, company_name,
        )
        return [], False

    snapshots = [_job_to_snapshot(j) for j in jobs]
    return snapshots, ok


def _job_to_snapshot(job: Job) -> dict:
    return {
        "title": job.title,
        "company": job.company,
        "url": job.url,
        "date_posted": job.date_posted,
        "location": job.location,
        "source": job.source,
        "work_mode": job.work_mode,
        "salary_lpa": job.salary_lpa,
        "jd_text": job.jd_text,
        "funding_stage": job.funding_stage,
        "has_esop": job.has_esop,
        "company_type": job.company_type,
        "notice_compatible": job.notice_compatible,
    }


def _resolve_path(data: object, path: str) -> list | None:
    if not path:
        return None
    parts = path.split(".")
    current = data
    for part in parts:
        if isinstance(current, dict):
            current = current.get(part)
        elif isinstance(current, list) and part.isdigit():
            idx = int(part)
            if idx < len(current):
                current = current[idx]
            else:
                return None
        else:
            return None
    return current if isinstance(current, list) else None


def _detect_work_mode(text: str) -> str:
    t = text.lower()
    if "remote" in t:
        return "remote"
    if "hybrid" in t:
        return "hybrid"
    return "onsite"


def _extract_job_items(data) -> list[dict]:
    if isinstance(data, list):
        return data
    if not isinstance(data, dict):
        return []
    for key in ("data", "jobs", "results", "items", "records", "hits"):
        val = data.get(key)
        if isinstance(val, list):
            return val
        if isinstance(val, dict):
            for inner_key in ("data", "jobs", "results", "items", "records", "hits"):
                inner = val.get(inner_key)
                if isinstance(inner, list):
                    return inner
    return []


async def _scrape_api(
    config: dict,
    session: httpx.AsyncClient,
    company_name: str,
    fallback_url: str,
) -> tuple[list[Job], bool]:
    url = config.get("url") or fallback_url
    method = (config.get("method") or "GET").upper()
    payload_template = config.get("payload_template")
    headers = config.get("headers") or {}
    result_path = config.get("result_path", "")
    mapping = config.get("mapping", {})

    if "Accept" not in headers:
        headers["Accept"] = "application/json"

    logger.info("[dynamic-api] start url=%s method=%s company=%s", url, method, company_name)

    all_jobs: list[Job] = []
    seen_ids: set[str] = set()
    http_ok = True

    for page in range(1, _MAX_PAGES + 1):
        try:
            body = None
            if method == "POST" and payload_template:
                import json as _json
                if isinstance(payload_template, str):
                    try:
                        body = _json.loads(payload_template)
                    except (_json.JSONDecodeError, ValueError):
                        body = None
                else:
                    body = dict(payload_template)
                if isinstance(body, dict):
                    body["page"] = page

            if method == "POST":
                r = await session.post(url, json=body, headers=headers, timeout=20.0)
            else:
                sep = "&" if "?" in url else "?"
                page_url = f"{url}{sep}page={page}&size={_PAGE_SIZE}"
                r = await session.get(page_url, headers=headers, timeout=20.0)

            if r.status_code >= 400:
                http_ok = False
                if page == 1:
                    continue
                break

            data = r.json()
            items = _resolve_path(data, result_path) if result_path else _extract_job_items(data)

            if not items or not isinstance(items, list):
                if page == 1:
                    continue
                break

            new_count = 0
            title_key = mapping.get("title", "title")
            url_key = mapping.get("url", "url")
            loc_key = mapping.get("location", "location")

            for item in items:
                if not isinstance(item, dict):
                    continue
                title = ""
                if title_key in item:
                    v = item[title_key]
                    title = str(v).strip() if isinstance(v, str) else ""
                if not title or len(title) < 3:
                    continue

                job_url = ""
                if url_key in item:
                    v = item[url_key]
                    job_url = str(v).strip() if isinstance(v, str) else ""
                if not job_url or not job_url.startswith("http"):
                    job_url = url

                location = ""
                if loc_key in item:
                    v = item[loc_key]
                    if isinstance(v, str):
                        location = v.strip()
                    elif isinstance(v, list) and v:
                        location = ", ".join(str(x) for x in v if isinstance(x, str))

                item_id = str(item.get("id") or item.get("slug", title))
                if item_id in seen_ids:
                    continue
                seen_ids.add(item_id)

                all_jobs.append(Job(
                    title=title[:150],
                    company=company_name,
                    url=job_url if job_url.startswith("http") else urljoin(url, job_url),
                    date_posted=datetime.now(tz=timezone.utc).isoformat(),
                    location=location,
                    source="custom_api",
                    work_mode=_detect_work_mode(f"{title} {location}"),
                    jd_text="",
                ))
                new_count += 1

            logger.info(
                "[dynamic-api] page=%d items=%d new=%d total=%d",
                page, len(items), new_count, len(all_jobs),
            )

            if len(items) < _PAGE_SIZE:
                break
            if new_count == 0:
                break
        except Exception as exc:
            logger.warning("[dynamic-api] page=%d error: %s", page, exc)
            http_ok = False
            if page == 1:
                continue
            break

    if all_jobs:
        logger.info("[dynamic-api] done company=%s total=%d", company_name, len(all_jobs))
    return all_jobs, http_ok


async def _scrape_dom(
    config: dict,
    company_name: str,
    fallback_url: str,
) -> tuple[list[Job], bool]:
    url = config.get("url") or fallback_url
    result_path = config.get("result_path", "")
    mapping = config.get("mapping", {})

    try:
        from playwright.async_api import async_playwright, TimeoutError as PWTimeout
    except ImportError:
        logger.warning("[dynamic-dom] playwright not installed")
        return [], False

    logger.info(
        "[dynamic-dom] start url=%s selector=%s company=%s",
        url, result_path, company_name,
    )

    card_sel = result_path
    if not card_sel:
        logger.warning("[dynamic-dom] no CSS selector in strategy")
        return [], True

    async with async_playwright() as pw:
        browser = await pw.chromium.launch(headless=True)
        try:
            ctx = await browser.new_context(
                user_agent=(
                    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
                    "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
                ),
                java_script_enabled=True,
            )
            page = await ctx.new_page()

            try:
                await page.goto(url, timeout=_TIMEOUT_MS, wait_until="domcontentloaded")
                try:
                    await page.wait_for_load_state("networkidle", timeout=_IDLE_WAIT_MS)
                except PWTimeout:
                    pass
            except PWTimeout:
                logger.warning("[dynamic-dom] page load timed out url=%s", url)
                return [], False

            from roleminer.scrapers.custom import _paginate
            await _paginate(page)

            try:
                count = await page.locator(card_sel).count()
            except Exception:
                logger.warning("[dynamic-dom] invalid selector: %s", card_sel)
                return [], True

            if count == 0:
                logger.info("[dynamic-dom] no elements matched selector=%s", card_sel)
                return [], True

            cards = await page.eval_on_selector_all(
                card_sel,
                """els => els.map(e => ({
                    text: (e.textContent || '').trim().substring(0, 500),
                    href: (e.querySelector('a[href]') || {}).href || null
                })).filter(e => e.text.length > 10)""",
            )

            jobs: list[Job] = []
            seen: set[str] = set()
            for card in cards:
                text = card.get("text", "")
                href = card.get("href")

                from roleminer.scrapers.custom import _looks_like_job_title, _clean_title, _extract_location
                title = _extract_title_from_lines(text)
                if not title:
                    continue

                job_url = href or url
                if not job_url.startswith("http"):
                    job_url = urljoin(url, job_url)

                if job_url in seen:
                    continue
                seen.add(job_url)

                location = ""
                loc_sel = mapping.get("location", "")
                if loc_sel:
                    location = _extract_location(text)

                jobs.append(Job(
                    title=_clean_title(title),
                    company=company_name,
                    url=job_url,
                    date_posted=datetime.now(tz=timezone.utc).isoformat(),
                    location=location,
                    source="custom",
                    work_mode=_detect_work_mode(text),
                    jd_text=text[:1000],
                ))

            logger.info("[dynamic-dom] done company=%s jobs=%d", company_name, len(jobs))
            return jobs, True
        finally:
            await browser.close()


def _extract_title_from_lines(text: str) -> str | None:
    from roleminer.scrapers.custom import _looks_like_job_title
    lines = [l.strip() for l in text.split("\n") if l.strip()]
    for line in lines:
        if _looks_like_job_title(line):
            return line
    return None
